site_name: IHC - Site do eCAC
site_url: https://interacao-humano-Computador.github.io/2026.1-Grupo01/
repo_url: https://github.com/Interacao-Humano-Computador/2026.1-Grupo01
repo_name: GitHub

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  logo: images/logo_cac.jpeg
  favicon: images/E-cac_icone.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.mark

nav:
  - Início: index.md

  - Planejamento: 
    - Heatmap:    Planejamento/heatmap.md
    - Sites Selecionados: Planejamento/sites-selecionados.md
    - Site Escolhido: Planejamento/site-escolhido.md
    - Cronograma: Planejamento/cronograma.md
    - Ferramentas: Planejamento/ferramentas.md
    - Processo de design: Planejamento/Processo_de_design.md

  - Avaliações:
    - Avaliação 1: Avaliações/grupo_1/Avaliação.md
    - Avaliação +1: Avaliações/grupo +1/exemplo.md

  - Atas:
    - Ata 1: atas/ata1.md
    - Modelo de Ata: atas/atagoverno.md

  - Analise de requisitos:
    - Analise de requisitos: analise de requisitos/exemplo.md

  - Apresentações:
    - Apresentação 1: Apresentações/exemplo.md
  
  - Design-avaliação-desenvolvimento:
    - Design: Design-avaliação-desenvolvimento/exemplo.md

  - Reuniões:
    - Reunião 1: Reuniões/reuniao1.md

  
